import React, { useState } from "react"
import Head from "next/head"
import Image from "next/image"
import logo from "../../public/logo.svg"

export default function Home() {
  const [isOpen, setIsOpen] = useState(false)
  return (
    <>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex">
      {/* Sidebar */}
      <div className={`w-64 bg-white px-8 py-4 border-r overflow-auto fixed lg:static duration-500 inset-y-0 left-0 lg:translate-x-0 transform ${isOpen ? "z-30 translate-x-0 ease-out transition-medium" : "-translate-x-full ease-in transition-medium"}`}>
        <div className="flex justify-between items-center">
          <Image src={logo} width={36} height={36} />
          <button className="text-gray-700 lg:hidden" onClick={() => setIsOpen(false)}>
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>

          </button>
        </div>
        <nav className="mt-8">
          <h3 className="text-sm font-semibold text-gray-600 uppercase tracking-wide">scrumboard</h3>
          <div className="mt-2 -mx-3">
            <a href="#" className="flex justify-between items-center px-3 py-2">
              <span className="text-sm font-medium text-gray-700">Backlog</span>
              <span className="text-xs font-semibold text-gray-700">23</span>
            </a>
            <a href="#" className="flex justify-between items-center px-3 py-2 bg-gradient-to-r from-purple-700 to-blue-500 rounded-lg">
              <span className="text-sm font-medium text-white">Active Sprints</span>
              <span className="text-xs font-semibold text-white">1</span>
            </a>
            <a href="#" className="flex justify-between items-center px-3 py-2">
              <span className="text-sm font-medium text-gray-700">Reports</span>
              <span className="text-xs font-semibold text-gray-700">13</span>
            </a>
          </div>
          <h3 className="mt-8 text-sm font-semibold text-gray-600 uppercase tracking-wide">Tags</h3>
          <div className="mt-2 -mx-3">
            <a href="#" className="flex justify-between items-center px-3 py-2">
              <span className="text-sm font-medium text-gray-700">Bug</span>
            </a>
            <a href="#" className="flex justify-between items-center px-3 py-2 rounded-lg">
              <span className="text-sm font-medium text-gray-700">New Feature</span>
            </a>
            <a href="#" className="flex justify-between items-center px-3 py-2">
              <span className="text-sm font-medium text-gray-700">Marketing</span>
            </a>
            <a href="#" className="flex justify-between items-center px-3 py-2">
              <span className="text-sm font-medium text-gray-700">Design</span>
            </a>
            <a href="#" className="flex justify-between items-center px-3 py-2">
              <span className="text-sm font-medium text-gray-700">Research</span>
            </a>
            <a href="#" className="flex justify-between items-center px-3 py-2">
              <span className="text-sm font-medium text-gray-700">Overdue</span>
            </a>
          </div>
        </nav>
      </div>
      <div className="flex flex-col flex-1 min-w-0">
        <div className="flex-shrink-0">
          <header className="flex flex-col px-6 border-b border-gray-200 py-3">
            <div className="min-w-0 flex items-center justify-between py-3">
              <div className="flex-shrink-0 flex items-center py-3">
                <button className="lg:hidden" onClick={() => setIsOpen(true)}>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                  </svg>

                </button >
                {/* Search Bar */}
                <div className="ml-4 lg:ml-0 relative w-64">
                  <span className="absolute inset-y-0 left-0 flex items-center pl-3">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6 text-gray-500">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
                    </svg>

                  </span>
                  <input className="block w-full text-sm border border-gray-400 rounded-md py-2 pl-10 pr-4 placeholder-gray-400" type="text" placeholder="Search" />
                </div>

              </div>
              {/* Icons */}
              <div className="ml-4 flex items-center">
                <button className="flex-shrink-0 text-gray-500 w-6 h-6">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
                  </svg>

                </button>
                <button className="ml-4 mr-2 flex-shrink-0">
                  <img className="w-9 h-9 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                </button>
              </div>
            </div>

            {/* Header Bottom */}
            <div className="flex-shrink-0 flex items-center justify-between py-2">
              <div className="sm:flex sm:items-center">
                <h2 className="text-lg font-medium text-gray-900">Assigness</h2>
                <div className="sm:ml-6 sm:mt-0 mt-1 flex items-center">
                  <span className="border-2 border-white rounded-full">
                    <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                  </span>
                  <span className="-ml-2.5 border-2 border-white rounded-full">
                    <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                  </span>
                  <span className="-ml-2.5 border-2 border-white rounded-full">
                    <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1611590027211-b954fd027b51?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                  </span>
                  <span className="-ml-2.5 border-2 border-white rounded-full">
                    <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                  </span>
                </div>
              </div>
              <div className="ml-8 flex items-center">
                <button className="pl-2 pr-4 py-2 text-sm font-medium hover:bg-gray-800 text-white bg-gray-900 rounded-md">Complete Sprint</button>
                <button className="ml-5 pl-2 pr-4 py-2 rounded-md hover:from-purple-600 hover:to-blue-500 text-sm font-medium text-white bg-gradient-to-r from-purple-700 to-blue-500 flex items-center">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v12m6-6H6" />
                  </svg>

                  <span>New Item</span>
                </button>
              </div>
            </div>
          </header>
        </div>


        {/* Main Content */}
        <div className="flex-1 bg-gray-50 overflow-auto">
          <main className="h-full p-3 inline-flex space-x-2 overflow-hidden">
            <div className="flex flex-col w-80 bg-transparent rounded-md">
              <h3 className="px-3 pt-3 pb-1 text-md font-medium text-gray-700 leading-tight font-mono">Todo</h3>
              <div className="flex-1 min-h-0 ">
                <ul className="pt-1 pb-3 px-3">
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-blue-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-blue-500 leading-tight">design</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-red-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-red-500 leading-tight">bug</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            {/* In Progress */}
            <div className="flex flex-col w-80 bg-transparent rounded-md">
              <h3 className="px-3 pt-3 pb-1 text-md font-medium text-gray-700 leading-tight font-mono">In Progress</h3>
              <div className="flex-1 min-h-0 ">
                <ul className="pt-1 pb-3 px-3">
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-blue-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-blue-500 leading-tight">design</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-pink-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-pink-500 leading-tight">research</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-green-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-green-700 leading-tight">new feature</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            {/* Testing */}
            <div className="flex flex-col w-80 bg-transparent rounded-md">
              <h3 className="px-3 pt-3 pb-1 text-md font-medium text-gray-700 leading-tight font-mono">Testing</h3>
              <div className="flex-1 min-h-0 overflow-y-auto">
                <ul className="pt-1 pb-3 px-3">
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-blue-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-blue-500 leading-tight">design</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-red-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-red-500 leading-tight">bug</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-purple-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-purple-500 leading-tight">marketing</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-blue-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-blue-500 leading-tight">design</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-orange-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-orange-500 leading-tight">overdue</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            {/* Done */}
            <div className="flex flex-col w-80 bg-transparent rounded-md">
              <h3 className="px-3 pt-3 pb-1 text-md font-medium text-gray-700 leading-tight font-mono">Done</h3>
              <div className="flex-1 min-h-0 ">
                <ul className="pt-1 pb-3 px-3">
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-orange-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-orange-500 leading-tight">overdue</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li className="mt-1">
                    <a href="#" className="block shadow p-5 rounded-md bg-white">
                      <div className="">
                        <div className="flex justify-between items-baseline">
                          <div className="bg-blue-200 rounded px-3 py-1">
                            <span className="uppercase text-sm font-medium text-blue-500 leading-tight">design</span>
                          </div>
                          <div className="flex items-center text-sm text-gray-400">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-4 h-4">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
                            </svg>
                            <span className="ml-2">2</span>
                          </div>
                        </div>
                        <div className="mt-3">
                          <p className="text-sm text-gray-800">Product illustration to symbolize bringing people together</p>
                        </div>
                        <div className="mt-3 flex items-center">
                          <span className="border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1526510747491-58f928ec870f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1530653535919-df7cc2bee192?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                          <span className="-ml-2.5 border-2 border-white rounded-full">
                            <img className="w-6 h-6 rounded-full object-cover" src="https://images.unsplash.com/photo-1598198414976-ddb788ec80c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=144&h=144&q=80" />
                          </span>
                        </div>
                      </div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </main>
        </div>
      </div>
    </div>
    </>
  )
}
